### ISSUE TITLE
Undefined variable in file ro_regonlinehandler.php

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/apcal#18] opened 2017-03-18 06:45 UTC
When I activate an online registration for an event (modules/apcal/ro_regonlinehandler.php), I get these errors:

```
Notice: Undefined variable: url in file /modules/apcal/ro_regonlinehandler.php line 143
Notice: Undefined variable: location in file /modules/apcal/ro_regonlinehandler.php line 157
```

**Comment by mambax7** [comment] 2017-03-20 10:11
This should be now fixed

**Comment by cesagonchu** [comment] 2017-03-22 22:45
With your corrections https://github.com/mambax7/apcal/commit/9810c4047955ce91fd7681c088c028b5833fc033 and https://github.com/mambax7/apcal/commit/dec6b993b5331d2d2bf35c59e40557201ca4bd51, I get the same errors:
Notice: Undefined variable: url in file /modules/apcal/ro_regonlinehandler.php line 145
Notice: Undefined variable: location in file /modules/apcal/ro_regonlinehandler.php line 159

**Comment by mambax7** [comment] 2017-03-23 11:03
I can't reproduce it. Please email me your data for the calendar, so I can test it here.

**Comment by cesagonchu** [comment] 2017-03-23 17:29
Ok that's fixed :-)

I think I had this error because my apcal file inside /uploads had not been deleted when I reinstalled the module.
It's not practical to delete this folder manually, every time.

**Closed as completed** 2017-03-23 17:29 UTC
